# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'T-bank_HW9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for T-bank_HW9
  pod 'Alamofire'

end
